### ISSUE TITLE
Technology Stack Diagram

### ISSUE THREAD

**Issue by falkonprods** [labs3/daoOS#1]
We need to create an architectural diagram that shows the  core stack  being  used: what  techs are  used for the front end, what is used on the backend for data storage, authentication, etc.

**Comment by pxydn** [comment]
in order for us to create a stack model for the data, we need a data model (issue #6)

for the frontend, we should use NextJS with Typescript.

**Comment by pxydn** [comment]
@marbiano & @MarianoArg, would you guys be up to work on the NextJS frontend?

**Comment by JMKJR** [comment]
If anymore help is needed for frontend, I have used Gatsby which is an alternative React based framework for static sites. NextJS wouldn't be difficult for me to ramp up on.

**Comment by MarianoArg** [comment]
@pxydn yep. I have some time now so I could start working on it. We'll use React with Next.Js and Typescript.
I can also work on the backend as well. We should define the data model we are gonna implement.

**Comment by marbiano** [comment]
@pxydn happy to help. Next.js is currently the most versatile option when it comes to building web apps _and_ websites, so it's a no-brainer in my humble yet _absolutely biased_ opinion.

Happy to onboard @JMKJR on Next.js if necessary.

**Comment by MarianoArg** [comment]
Same here, I can help with the front and the backend as well.

**Comment by JMKJR** [comment]
> @pxydn happy to help. Next.js is currently the most versatile option when it comes to building web apps _and_ websites, so it's a no-brainer in my humble yet _absolutely biased_ opinion.
> 
> Happy to onboard @JMKJR on Next.js if necessary.

I agree! No argument from me there :) . I wasn't suggesting Gatsby, it doesn't make sense in this situation as it is for generating static websites. I was just mentioning my similar frontend experience React/Material UI/Gatsby was the stack I used before. Thanks!

Also available and interested in working with backend. Experience: NodeJS/Express/Hapi, ASP.NET. No smart contract experience but I've been working on clarity tutorials. Ready and willing to help with anything and everything.

**Comment by pxydn** [comment]
NextJS it is then! 😄

we can have a call to discuss L³ UI's in general on Discord soon (time/date TBD).

@JMKJR you have experience with backend stuff - would you be interested in the DDNS/metaverse projects too? and maybe apex too. they will all be highly server/Docker-based - may be in your area of expertise?

if we need a backend for this, we should maybe start to get used to using [Deno](https://deno.land). i'm thinking we won't, but JIC :)

**Comment by JMKJR** [comment]
> NextJS it is then! 😄
> 
> we can have a call to discuss L³ UI's in general on Discord soon (time/date TBD).
> 
> @JMKJR you have experience with backend stuff - would you be interested in the DDNS/metaverse projects too? and maybe apex too. they will all be highly server/Docker-based - may be in your area of expertise?
> 
> if we need a backend for this, we should maybe start to get used to using [Deno](https://deno.land). i'm thinking we won't, but JIC :)

Haha I love the ambitious L3 agenda! Of course, that's what I'm here for, to help out anywhere I can. Docker specifically isn't an area of expertise for me, the devops team within my organization handles that type of infrastructure for us. However, more than happy to learn anything needed. Wherever our blind spots are, we are smart people and will figure it out and help each other as needed! ;)

Glad you mentioned Deno! Hadn't heard of it before until just now and it solves a problem I literally just ran into at my company where we need to sandbox certain server nodes in our organization where Node presents security challenges. Thanks, just another one of the amazing benefits of collaboration!

**Comment by pxydn** [comment]
### ideas

- the majority of backend functions and storage should be controlled by smart contracts for trust reasons.
- after this project has a mainnet version, we should create a SIP and standardise the API used to interface with a DAO. this will allow other 3rd party UIs to be built that integrate with daoOS. a sorta DAO standard for DAOs on Stacks

opinions?

**Comment by pxydn** [comment]
@LNow has created a stack diagram which is good enough for this issue. ty! great job.

![DAO_Container_Diagram](https://user-images.githubusercontent.com/67651251/115570150-c9999d00-a2b5-11eb-9348-de0527a855c9.png)
